### ISSUE TITLE
Building MVC4ServicesDB project fails

### ISSUE THREAD

**Issue by iamandycohen** [jamiekurtz/Mvc4ServicesBook#1]
I get the following error:

Error   47  SQL71566: Microsoft.Data.Tools.Schema.Sql.SchemaModel.SqlFilegroup cannot not be set on both the Microsoft.Data.Tools.Schema.Sql.SchemaModel.SqlTable and the clustered Microsoft.Data.Tools.Schema.Sql.SchemaModel.SqlPrimaryKeyConstraint.    E:\gitted\MVC4ServicesBook\src\MVC4ServicesDb\dbo\Tables\User.sql   10  6   MVC4ServicesDb

**Comment by jamiekurtz** [comment]
Thanks, I'll take a look.
