### ISSUE TITLE
No Front End?

### ISSUE THREAD

**Issue by RAGolko** [jamiekurtz/Mvc4ServicesBook#4]
I can't run the sample because I get a 404 not found... there is no front end to this or am I missing something?  What's supposed to launch when you run the webapi project?

**Comment by sukumarraju** [comment]
Any tool that can make HTTP request is the client.

Any browser (IE, Firefox or Chrome) or Fiddler can invoke the service. Simple run the service and type the correct URI in the address bar to see the data or debug.

**Comment by jamiekurtz** [comment]
Yes, thank you sukumarraju. I didn't include any kind of real client code in the book source. But you can, as sukumarraju pointed out, use your browser to "see" the API. For example, you can set the startup project as the MVC4ServicesBook.Web.Api project, and then in the Project Properties -> Debug page, you can set the starting URL as something interesting - e.g. /api/categories.

I typically use the Chrome Advanced REST Client extension or Fiddler to experiment and test the various URLs and methods.
